@startuml
'https://plantuml.com/class-diagram

class UAbilitySystemComponent
{
# FGameplayAbilitySpecContainer ActivatableAbilities
# FActiveGameplayEffectsContainer ActiveGameplayEffects
- TArray<TObjectPtr<UAttributeSet>>	SpawnedAttributes
}

class UGameplayAbility
class UGameplayEffect
class UAttributeSet


UAbilitySystemComponent <--o UGameplayAbility 
UAbilitySystemComponent <--o UAttributeSet 
UAbilitySystemComponent <--o UGameplayEffect 



@enduml